services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ROCKET_PORT=8000
      - ROCKET_ADDRESS=0.0.0.0
    ports:
      - "8000:8000"
    depends_on:
      - redis
  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
